sudo: required
language: php
php:
  - 7.2
before_install:
  - cd CodeDesignInitiative/cdweb1801
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - php composer.phar install
  - ./vendor/bin/jigsaw build production
  - cp _redirects build_production/_redirects
  - wget -qO- 'https://cli.netlify.com/download/latest/linux' | tar xz

cache:
  directories:
    - $HOME/.composer/cache/files

script:
- ./netlifyctl -A $NETLIFY_TOKEN deploy -s "code-design-initiative.netlify.com" -P "build_production"
